name: Deploy go backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t zebnox/golang_backend .
      - name: Push docker image
        run: docker push zebnox/golang_backend:latest
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull zebnox/golang_backend:latest
      - name: Delete old docker container
        run: docker rm -f golang-backend
      - name: Checkout Source  
        uses: actions/checkout@v4
      - name: Run shell file
        run: sh ./start.sh
      - name: Run docker container
        run: docker run -d --env-file /home/ubuntu/.env -p 8080:8080 --name golang-backend zebnox/golang_backend
